SharedFlags= -shared -fPIC
SyntaxFlags= -W -Wall

SourceRootDir= /home/ntx/Plocha/MultiServer
ApplicationInclude = $(SourceRootDir)/Application
DataStructInclude = $(SourceRootDir)/DataArrays
HandlingInclude = $(SourceRootDir)/Handling
SignalInclude = $(SourceRootDir)/Signal
SharedInclude = $(SourceRootDir)/Shared
SimpleLogInclude = $(SourceRootDir)/SimpleLog
SocketsInclude = $(SourceRootDir)/Sockets
ThreadsInclude = $(SourceRootDir)/Threads
ProtocolInclude = $(SourceRootDir)/Protocol
ConfigMgrInclude = $(SourceRootDir)/ConfigMgr

IncludeDirs= -I $(SourceRootDir) -I $(ApplicationInclude) -I $(DataStructInclude) -I $(HandlingInclude) -I $(SignalInclude) -I $(SharedInclude) -I $(SimpleLogInclude) -I $(SocketsInclude) -I $(ThreadsInclude) -I $(ProtocolInclude) -I $(ConfigMgrInclude)
 
Flags += $(IncludeDirs)

black= tput setaf 0
red= tput setaf 1
green= tput setaf 2
orange= tput setaf 3
blue= tput setaf 4
bold= tput bold
normal= tput sgr0
